Numpy 배열 속성 지정

In [19]:
import numpy as np
np.random.seed(0) # 재현 가능성을 위한 시드 값

x1 = np.random.randint(10, size=6) # 1차원의 배열
x2 = np.random.randint(10, size=(3,4)) # 2차원 배열
x3 = np.random.randint(10, size=(3,4,5)) # 3차원 배열

각 배열은 속성으로 ndim(차원의 개수), shape(각 차원의 크기), size(전체 배열 크기)를 가지고 있다.

In [7]:
print("x3 ndim:", x3.ndim)
print("x3 shape", x3.shape)
print("x3 size ", x3.size)
print("x3 dtype", x3.dtype)
print("itemsize", x3.itemsize)
print("nbytes = itemsize * size")
print("nbytes", x3.nbytes)

x3 ndim: 3
x3 shape (3, 4, 5)
x3 size  60
x3 dtype int64
itemsize 8
nbytes = itemsize * size
nbytes 480


배열 인덱싱 : 단일 요소에 접근하기

In [10]:
print(x1)
print(x1[0])
print(x1[4])
print(x1[-1])
print(x1[-2])

[5 0 3 3 7 9]
5
7
9
7


In [14]:
print(x2)
# 2차원 Data 호출 방법
print(x2[0][0])
print(x2[0,0])

print(x2[2,-3:])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3
3
[6 7 7]


Numpy 는 파이썬과 다르게 고정 타입을 가진다.
- 정수배열에 부동 소수점을 입력하면 정수type 으로 변환시킨다.

In [20]:
print(x3)
x3[0,0,0]=311.141592
print()
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]

[[[311   1   5   9   8]
  [  9   4   3   0   3]
  [  5   0   2   3   8]
  [  1   3   3   3   7]]

 [[  0   1   9   9   0]
  [  4   7   3   2   7]
  [  2   0   0   4   5]
  [  5   6   8   4   1]]

 [[  4   9   8   1   1]
  [  7   9   9   3   6]
  [  7   2   0   3   5]
  [  9   4   4   6   4]]]


# 배열 슬라이싱 : 하위 배열에 접근하기

x[start:stop:step]

### 1차원 하위 배열

In [22]:
x= np.arange(10)
print(x)

# 첫 5개 요소
print(x[:5])

# 인덱스 5 다음 요소들
print(x[5:])

# 중간 하위 배열
print(x[4:7])

# 하나 걸러 하나씩 구성
print(x[::2])

# 인덱스 1에서 시작해 하나 걸러 하나씩
print(x[1::2])

print("음수인 경우")
# 배열을 거꾸로 나열
print(x[::-1])

# 인덱스 5부터 하나 걸러 하나씩 거꾸로 나열
print(x[5::-2])


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
음수인 경우
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


### 다차원 하위 배열

In [23]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [24]:
x2[:2, :3]

array([[3, 5, 2],
       [7, 6, 8]])

In [26]:
# 3개행, 2개 열
x2[:3, :2]

array([[3, 5],
       [7, 6],
       [1, 6]])

In [27]:
x2[ ::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

### 배열 슬라이스는 뷰를 반환한다.
- 데이터 변경 시 주의할 것
- 원본을 변경하고 싶지 않을 때는 copy() 메서드 활용

In [35]:
print(x2)
x2_sub= x2[:2,:2]
x2_sub[0,0]=96
print("원본이 바뀐것을 확인할 수 있다")
print(x2_sub)
print(x2)

[[96  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
원본이 바뀐것을 확인할 수 있다
[[96  5]
 [ 7  6]]
[[96  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [38]:
# copy() 메서드
x2_sub_copy=x2[:2, :2].copy()
print(x2_sub_copy)
x2_sub_copy[0,0] = 0
print("원본이 바뀌지 않는다")
print(x2_sub_copy)
print(x2)

[[96  5]
 [ 7  6]]
원본이 바뀌지 않는다
[[0 5]
 [7 6]]
[[96  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### 배열 재구조화
- reshape() 메서드 활용
- 변경 전,후 배열의 규모가 일치해야한다.

In [40]:
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 배열 연결 및 분할

#### 배열 연결



##### np.concatenate

In [44]:
x= np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])


array([1, 2, 3, 3, 2, 1])

In [46]:
# 한번에 여러배열 연결
z=[99,99,99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [47]:
# 2차원 배열에서의 연결
grid = np.array([[1,2,3],
                 [4,5,6]])
print(np.concatenate([grid,grid]))

# 두번째 축을 따라 연결
print(np.concatenate([grid,grid],axis=1))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


##### np.hstack , np.vstack, 
  - 혼합된 차원의 배열로 작업할 때는 hstack(수직스택) 혹은 vstack(수평스택) 함수 사용이 더 명확하다

In [48]:
x=np.array([1,2,3])
grid=np.array([[9,8,7],
               [6,5,4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [49]:
y=np.array([[99],
            [99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

#### 배열 분할

##### np.split

In [62]:
x=[1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x, [3,6])
print(x1, x2 , x3)
x1,x2,x3 = np.split(x, [3,5])
print(x1, x2 , x3)

[1 2 3] [99 99  3] [2 1]
[1 2 3] [99 99] [3 2 1]


##### np.hsplit, np.vsplit
- N개의 분할점은 N+1개의 하위 배열을 만든다.

In [63]:
grid= np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
upper, lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [65]:
left, right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
