### UFuncs 소개

In [1]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
  output = np.empty(len(values))
  for i in range(len(values)):
    output[i]=1.0/values[i]
  return output

values = np.random.randint(1,10,size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [3]:
big_array = np.random.randint(1,100, size=1000000)
%timeit compute_reciprocals(big_array)

1 loop, best of 5: 2.06 s per loop


In [5]:
print(compute_reciprocals(values))
print(1.0/values)
%timeit(1.0/big_array)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]
1000 loops, best of 5: 1.51 ms per loop


### NumPy 유니버설 함수(UFuncs)

#### 배열 산술 연산

In [7]:
x=np.arange(4)
print(" x     =",x)
print(" x + 5 =",x+5)
print(" x - 5 =",x-5)
print(" x * 2 =",x*2)
print(" x / 2 =",x/2)
print(" x // 2 =",x//2)

 x     = [0 1 2 3]
 x + 5 = [5 6 7 8]
 x - 5 = [-5 -4 -3 -2]
 x * 2 = [0 2 4 6]
 x / 2 = [0.  0.5 1.  1.5]
 x // 2 = [0 0 1 1]


#### 절댓값 함수

In [8]:
x=np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

In [9]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [10]:
np.abs(x)

array([2, 1, 0, 1, 2])

#### 삼각함수

In [11]:
theta = np.linspace(0, np.pi, 3)
print("theta     =",theta)
print("sin(theta)=",np.sin(theta))
print("con(theta)=",np.cos(theta))
print("tan(theta)=",np.tan(theta))

theta     = [0.         1.57079633 3.14159265]
sin(theta)= [0.0000000e+00 1.0000000e+00 1.2246468e-16]
con(theta)= [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)= [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


#### 지수와 로그

In [12]:
x=[1,2,3]
print("x    =",x)
print("e^x  =",np.exp(x))
print("2^x  =",np.exp2(x))
print("3^x  =",np.power(3,x))

x    = [1, 2, 3]
e^x  = [ 2.71828183  7.3890561  20.08553692]
2^x  = [2. 4. 8.]
3^x  = [ 3  9 27]


In [14]:
x=[1,2,3,4]
print("x        =",x)
print("ln(x)    =",np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 3, 4]
ln(x)    = [0.         0.69314718 1.09861229 1.38629436]
log2(x)  = [0.        1.        1.5849625 2.       ]
log10(x) = [0.         0.30103    0.47712125 0.60205999]


#### 고급 UFunc 기능

##### 1. 출력지정
대규모 연산인 경우, 연산 결과를 저장할 배열을 지정하는 것이 유용할 때가 있다.

In [15]:
x= np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [16]:
# 배열 뷰와 함께 사용하기
y=np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


##### 2. 집계
이항 ufuncs 의 경우 배열을 특정 연산으로 축소하고자 한다면 <b>reduce</b> 메서드 활용

In [21]:
# 모든 요소의 합 반환하기
x=np.arange(1,6)
np.add.reduce(x)

15

In [22]:
# 모든 요소의 곱 반환하기
x= np.arange(1,6)
np.multiply.reduce(x)

120

In [23]:
# 계산의 중간과정을 저장하고 싶으면 accmulate 사용
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [24]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

##### 3. 외적

In [2]:
x=np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])