In [1]:
import numpy as np
L = np.random.random(100)
sum(L)

49.75501604214282

In [2]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit sum(L)

10 loops, best of 5: 154 ms per loop
100000 loops, best of 5: 16.9 µs per loop


In [5]:
np.min(big_array), np.max(big_array)
min(big_array), max(big_array)

%timeit np.min(big_array)
%timeit min(big_array)

The slowest run took 9.28 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 5: 472 µs per loop
10 loops, best of 5: 94.4 ms per loop


### 다차원 집계

In [6]:
M = np.random.random((3,4))
M

array([[0.08278847, 0.6681746 , 0.34125139, 0.44004632],
       [0.15757181, 0.09599682, 0.29134212, 0.16182849],
       [0.15068957, 0.46499369, 0.2725439 , 0.91124701]])

In [7]:
M.sum

<function ndarray.sum>

In [12]:
# 각 열 기준 
M.min(axis=0)

array([0.08278847, 0.09599682, 0.2725439 , 0.16182849])

In [11]:
# 각 행 기준
M.min(axis=1)

array([0.08278847, 0.09599682, 0.15068957])

In [ ]:
# 평균
np.mean
