## 브로드캐스팅 소개

In [1]:
import numpy as np
a = np.array([0,1,2])
b = np.array([5,5,5])
a+b

array([5, 6, 7])

In [ ]:
a+5

array([5, 6, 7])

In [ ]:
M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

### 브로드캐스팅 규칙
- 규칙 1 : 두 배열의 차원수가 다르면 더 작은 수의 차원을 가진 배열 형상의 앞쪽을 1로 채운다

- 규칙 2 : 두 배열의 형상이 어떤 차원에서도 일치하지 않는다면 해당 차원의 형상이 1인 배열이 다른 형상과 일치하도록 늘어난다.

- 규칙 3: 임의의 차원에서 크기가 일치하지 않고 1 도 아니라면 오류가 발생한다

#### 브로드캐스팅 예제 1

In [ ]:
M=np.ones((2,3))
a=np.arange(3)
print("M: \n",M)
print("a: \n",a)
# 규칙 1에 따라 배열 a 가 더 작은 차원을 가지므로 왼쪽을 1로 채운다.
# 규칙 2에 따라 차원이 일치하지 않으므로 2차원이 되도록 늘린다.
# 모양이 일치하면 최종 형상이 2,3 이 된다는 것을 알 수 있다
M+a

M: 
 [[1. 1. 1.]
 [1. 1. 1.]]
a: 
 [0 1 2]


array([[1., 2., 3.],
       [1., 2., 3.]])

#### 브로드캐스팅 예제 2

In [ ]:
a= np.arange(3).reshape((3,1))
b = np.arange(3)
print(a)
print(b)
# 규칙 1에 따라 b 의 형상에 1을 덧붙인다.
# 규칙 2 에 따라 각 차원을 대응하는 배열의 크기에 일치시킨다
a+b

[[0]
 [1]
 [2]]
[0 1 2]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

#### 브로드캐스팅 예제 3
- 호환되지 않는 경우

In [ ]:
M = np.ones((3,2))
a=np.arange(3)
M+a

ValueError: ignored

#### 실전 브로드캐스팅

In [2]:
import numpy as np
X=np.random.random((10,3))

In [3]:
Xmean = X.mean(0)
Xmean

array([0.52126262, 0.41534306, 0.39600815])

In [4]:
X_centered = X-Xmean
X_centered

array([[-0.00264426, -0.35310416,  0.25514171],
       [-0.37872899,  0.53450819, -0.29072564],
       [ 0.44549139, -0.06689163,  0.117366  ],
       [-0.20600013,  0.33562609, -0.2917414 ],
       [-0.0402145 , -0.13900609,  0.57080064],
       [-0.37958279,  0.13316996, -0.08469338],
       [ 0.03854407, -0.1746838 ,  0.20191179],
       [ 0.08082107, -0.13956485, -0.07270251],
       [ 0.32264789,  0.24433778, -0.09983787],
       [ 0.11966624, -0.37439149, -0.30551934]])

In [5]:
X_centered.mean(0)

array([ 4.44089210e-17, -9.43689571e-17, -3.33066907e-17])